### ISSUE TITLE
Plans for selling these?

### ISSUE THREAD

**Issue by jamesmunns** [jgillick/ThunderPack#3]
Hey there! This looks exactly like something I was planning to make (for a WS2812 dog collar), and I was wondering if you planned on selling these anywhere like Tindie.

For my use, either the STM32L0 or the new STM32F4 parts should work (I'll write the firmware in Rust instead of CircuitPython), so either revision works for me!

Thanks for sharing an awesome project!

**Comment by jgillick** [comment]
Yeah, I was considering doing a small run and trying to sell a few on Tindie. I'm finishing up some of the remaining testing/documenting and then will put an order in and let you know.

If you plan to write some firmware in Rust, I'd love to get a boilerplate I could include in the examples sections. I've been planning to try learning Rust soon.

**Comment by jamesmunns** [comment]
Sure! I recently did something similar for the [OtterPill](https://github.com/jamesmunns/OtterPill-rs/), the stm32 family is super well supported in Rust, so happy to contribute some boilerplate/examples.

I live in Germany, but happy to pay for international shipping as well, though it would be good to buy a couple boards at once :) probably count me in for 3-5, depending on the cost of each. I have a bunch of 18650s laying around, so i’d be interested in that version.

**Comment by jgillick** [comment]
OtterPill is also a board I've been wanting to play with. Really nice design and I'm impressed with the cost the creator was able to get it down to.

Thanks for letting me know how many you're interested in. I'll let you know the price when I get the order setup with PCBWay.

**Comment by mattpackwood** [comment]
Do you have a Tindie ID?

**Comment by jgillick** [comment]
Not yet, but I'll be setting that up very soon. I should be getting the first batch of boards from the manufacturer sometime around middle of this month.

**Comment by mattpackwood** [comment]
Hopefully, you can let me know when that happens!

**Comment by mattytrentini** [comment]
Wouldn't mind getting my hands on one of these to create a MicroPython board definition. There are already existing [STM32F11 boards](https://github.com/micropython/micropython/tree/master/ports/stm32/boards) so it should be trivial...so yes, please let us know when you put sell these on Tindie!

**Comment by jgillick** [comment]
PCBWay is running a little behind as they had a problem with sourcing one of the components. I'll let you know the updated timeline as soon as they get that to me.

@mattytrentini Yeah, creating a MicroPython board definition for this should be pretty straight forward!

**Comment by jgillick** [comment]
Good news! I just received the small production run from PCBWay and they're beautiful. I'm still waiting on the shipment of batteries, but once I get them I'll be listing these for sale on my Tindie shop. (Shipping amid COVID is making things take much longer to receive than usual).

Tindie Shop: https://www.tindie.com/stores/jeremy/

![IMG_9412](https://user-images.githubusercontent.com/35894/83977706-75611680-a8b7-11ea-9f15-b8f32389b54a.JPG)

**Comment by jgillick** [comment]
It took MUCH longer to get this setup than expected, but I have the product listed on Tindie:
https://www.tindie.com/products/jeremy/thunderpack-18650/

Let me know if you need any help. This is my first time setting up a shop on Tindie.
